# Generated by Django 5.1.7 on 2025-03-23 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradress',
            old_name='postal_code',
            new_name='post_code',
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата платежу')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Готівка'), ('Рахунок', 'iban')], default='card', max_length=10, verbose_name='Метод платежу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
