# Generated by Django 5.1.7 on 2025-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_postal_code_useradress_post_code_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картка'), ('Готівка', 'cash'), ('iban', 'Рахунок')], default='card', max_length=10, verbose_name='Метод платежу'),
        ),
    ]
